### ISSUE TITLE
cant select text in "print preview" mode

### ISSUE THREAD

**Issue by milahu** [evnbr/bindery#127]
**Describe the bug**
selecting text in "print preview" mode does not work.
rightclick on text + "inspect" = these elements:

```html
<div class="bindery-page bindery-left"></div>

<div class="bindery-page bindery-right"></div>
```

**Expected behavior**
allow selecting text in "print preview" mode

**Quickfix**
fixed by removing this CSS block

```css
    .bindery-show-bleed .bindery-page:after {
      content: "";
      outline: 1px dotted rgba(0, 255, 255, 0.7);
      position: absolute;
      left: 0;
      right: 0;
      bottom: 0;
      top: 0;
      z-index: 99;
    }
```
