### ISSUE TITLE
running header ignores top margin

### ISSUE THREAD

**Issue by milahu** [evnbr/bindery#128]
**Describe the bug**
the "running header" always has the same Y position
regardless of `binderyOptions.pageSetup.margin.top`

**Expected behavior**
running header should honor `pageSetup.margin.top`

**Additional context**

actual CSS

```css
  .bindery-running-header {
    top: 0.25in;
  }
```

expected CSS

```css
  .bindery-running-header {
    top: var(--bindery-margin-top);

    /* FIXME remove this workaround.
    move page-content down to make room for header */
    margin-top: -1.5em;
  }
```
