### ISSUE TITLE
FullPage rotatation option

### ISSUE THREAD

**Issue by teddybradford** [evnbr/bindery#18]
I'd like to have some full page figures rotated. At first I tried doing this purely through CSS, but it looks like it'll take some JS to work properly.

The CSS I tried:

```css
.hero-figure {
  width: 100%;
  height: 100%;
  margin: 0;
  transform: rotate(90deg) translate(0, -100%);
  transform-origin: top left;
}
```

Results in:

![image](https://user-images.githubusercontent.com/3684553/29379500-b8b3a934-8290-11e7-818c-b2539844b00c.png)

As you can see, the width and height of the figure are effectively swapped from the transform; the width of the figure is the height of the page, and the height of the figure is width of the page.
