### ISSUE TITLE
display just the print button

### ISSUE THREAD

**Issue by YuccaV2** [evnbr/bindery#50]
Bravo for the evolutions and in particular the possibility to open on a view "print" directly. Is there a solution to not display all controls, just the "print" button and change the label of this button by "print or save pdf" for example. Overall, it would be nice to be able to set the controls that are displayed.

I need to customize the interface a bit, so I removed the control display and added a "print or save pdf" button that starts printing correctly, but it appears on the printed document. How to add elements (texts or others) without being printed? I tried with @media print without success.

**Comment by evnbr** [comment]
Now that controls are pulled out separately, makes sense that they should be customizable. Will try and add that in within the next few weeks.

But in the mean time — adding your own button like you describe *should* work fine: either (a) hide when printing 

```css
.my-controls {
  display: block;
}

@media print {
  .my-controls {
    display: none;
  }
}
```

or (b) only show on `screen`
```css
.my-controls {
  display: none;
}

@media screen {
  .my-controls {
    display: block;
  }
}
```
