### ISSUE TITLE
White borders

### ISSUE THREAD

**Issue by danielepolencic** [evnbr/bindery#91]
Context: I use Bindery with the headless puppeteer.

If I click on "Print" in a browser, I can see the full PDF, perfectly printed.

![image](https://user-images.githubusercontent.com/1130499/106907278-0a632a80-6739-11eb-91ba-84022291085d.png)

If I trigger the `.pdf` API from puppeteer, I can see white borders.

<img width="763" alt="Screenshot 2021-02-04 at 22 34 54" src="https://user-images.githubusercontent.com/1130499/106907454-3aaac900-6739-11eb-9884-b286c4504387.png">

I tried to add:

```css
.📖-zoom-content {
  background: yellow;
}

.📖-print-sheet {
  background: red;
}

.📖-spread-wrapper {
  background: blue;
}
```

And narrowed down that the issue starts in `.spread-wrapper`.

<img width="757" alt="Screenshot 2021-02-04 at 22 27 29" src="https://user-images.githubusercontent.com/1130499/106907135-dee04000-6738-11eb-9eec-9dd29efaa520.png">

I tried to add a `width: 100% !important` to `.📖-spread-wrapper` and things seem to be better. But still not ok.

<img width="913" alt="Screenshot 2021-02-04 at 22 28 21" src="https://user-images.githubusercontent.com/1130499/106907072-d12aba80-6738-11eb-8aaa-df9ead82cbaa.png">

We've tried to fix this for a long time. However, we were not able to do so.
I understand that this is not a bug with Bindery.js (we're pretty sure that it might be puppeteer), but I was wondering if there any suggestion or any feedback on what we could do to make it work.

the fact that the same chromium instance can generate a valid PDF (in non-headless mode) and a PDF with border (headless) suggests that the issue might be in the "export to PDF" function. However, what CSS property that causes such discrepancy is a bit of a mystery.

Anything that we should try next? Have you seen anything like that?

Happy to close the ticket if not relevant.

Thanks.

**Comment by danielepolencic** [comment]
For some weird reason, only works with:

```css
@page {
  size: 210mm 297mm !important;
}
.📖-print-sheet {
  width: var(--bindery-page-width) !important;
  height: var(--bindery-page-height) !important;
} 
```

The `!important`s have to be there.
